### ISSUE TITLE
大佬，这个后台业务逻辑是用什么实现的？

### ISSUE THREAD

**Issue by SHEN-XM** [jiaopianjun/social#1]
大佬，这个后台业务逻辑是用什么实现的？java还是什么，能提供么，哈哈哈哈，膜拜大佬

**Comment by niushiqi** [comment]
> 大佬，这个后台业务逻辑是用什么实现的？java还是什么，能提供么，哈哈哈哈，膜拜大佬

php一天能做出一个后台

**Comment by WO-NAAA** [comment]
大佬这怎么打开

**Comment by SHEN-XM** [comment]
1
